/**
 * การตั้งค่ากลุ่มไลน์การผลิตและโครงสร้างตาราง (Line Groups & Tab Lines Configuration)
 * - กำหนดรายชื่อ Line การผลิตหลักและย่อยแยกตามกะ (/A, /B, /D)
 * - กำหนดการจัดหมวดหมู่หน้า Tab (Macro PCN, FPC, SMT, QA, etc.)
 * - กำหนดสูตรการรวมยอด VDS Formula Registry
 */
const MACRO_PCN_DIRECT_LINES = [
  "HOT PRESS/A",
  "HOT PRESS/B",
  "HOT PRESS/D",
  "VAC/A",
  "VAC/B",
  "VAC/D",
  "BLK/A",
  "BLK/B",
  "BLK/D",
  "F-LAM/A",
  "F-LAM/B",
  "F-LAM/D",
  "OST/A",
  "OST/B",
  "OST/D",
  "AVI/K2/A",
  "AVI/K2/B",
  "AVI/K2/D",
  "AT_FRONT/A",
  "AT_FRONT/B",
  "AT_FRONT/D",
  "AT_VAC/A",
  "AT_VAC/B",
  "AT_VAC/D",
  "AT_LAM/A",
  "AT_LAM/B",
  "AT_LAM/D",
  "LINE A_FINAL/A",
  "LINE A_FINAL/B",
  "LINE A_FINAL/D",
  "LINE B_GEN/A",
  "LINE B_GEN/B",
  "LINE B_GEN/D",
  "LINE B_NON/A",
  "LINE B_NON/B",
  "LINE B_NON/D",
  "LINE C/A",
  "LINE C/B",
  "LINE C/D",
  "LINE D/A",
  "LINE D/B",
  "LINE D/D",
  "MOTA_A/A",
  "MOTA_A/B",
  "MOTA_A/D",
  "MOTA_G/A",
  "MOTA_G/B",
  "MOTA_G/D",
  "MOTB_A/A",
  "MOTB_A/B",
  "MOTB_A/D",
  "MOTB/A",
  "MOTB/B",
  "MOTB/D",
  "MOTB_G/A",
  "MOTB_G/B",
  "MOTB_G/D",
  "MOTD/A",
  "MOTD/B",
  "MOTD/D",
  "MOTC/A",
  "MOTC/B",
  "MOTC/D",
  "ASTP_A/A",
  "ASTP_A/B",
  "ASTP_A/D",
  "ASTP_G/A",
  "ASTP_G/B",
  "ASTP_G/D",
  "X-Ray/A",
  "X-Ray/B",
  "X-Ray/D",
  "MAS/A",
  "MAS/B",
  "MAS/D",
  "REW/A",
  "REW/B",
  "REW/D",
  "BLK-1/A",
  "BLK-1/B",
  "BLK-1/D",
  "BLK-2/A",
  "BLK-2/B",
  "BLK-2/D",
  "ASY1_A/A",
  "ASY1_A/B",
  "ASY1_A/D",
  "ASY1_G/A",
  "ASY1_G/B",
  "ASY1_G/D",
  "ASY2/A",
  "ASY2/B",
  "ASY2/D",
  "ASY3/A",
  "ASY3/B",
  "ASY3/D",
  "AIX-ASY/A",
  "AIX-ASY/B",
  "AIX-ASY/D",
  "SMT_LAM/A",
  "SMT_LAM/B",
  "SMT_LAM/D",
  "MDLAM/A",
  "MDLAM/B",
  "MDLAM/D",
  "LAM MD/A",
  "LAM MD/B",
  "LAM MD/D",
  "AELT/A",
  "AELT/B",
  "AELT/D",
  "AIX-MOT/A",
  "AIX-MOT/B",
  "AIX-MOT/D",
  "AIX-BLK/A",
  "AIX-BLK/B",
  "AIX-BLK/D",
  "EXC_FPC/A",
  "EXC_FPC/B",
  "EXC_FPC/D",
];

const MACRO_PCN_INDIRECT_LINES = [
  "HR/D",
  "ACC/D",
  "STR/D",
  "STR/A",
  "STR/B",
  "LOG_FPC/A",
  "LOG_FPC/B",
  "LOG_FPC/D",
  "LOG_SHP/D",
  "LOG_SMT/A",
  "LOG_SMT/B",
  "LOG_SMT/D",
  "LOG_WH/D",
  "SE/D",
  "SHE/D",
  "AUT/D",
  "PLN/A",
  "PLN/B",
  "PLN/D",
  "CR/D",
  "PTE_OFF/D",
  "PTE_FAC/A",
  "PTE_FAC/B",
  "PTE_FAC/D",
  "PTE_MAC/A",
  "PTE_MAC/B",
  "PTE_MAC/D",
  "PTE_CAL/D",
  "DIE/A",
  "DIE/B",
  "DIE/D",
  "TOOL_FPC/A",
  "TOOL_FPC/B",
  "TOOL_FPC/D",
  "FIX/A",
  "FIX/B",
  "FIX/D",
  "TOOL_SMT/A",
  "TOOL_SMT/B",
  "TOOL_SMT/D",
  "TSTE-NPM/D",
  "TECH-NPM/D",
  "FA-NPM/D",
  "FPS/D",
  "TCO/D",
  "AI/D",
  "QE/D",
  "SVOQI/D",
  "SVIQI/D",
  "QA-IPQC/A",
  "QA-IPQC/B",
  "QA-IPQC/D",
  "IQI_M/A",
  "IQI_M/B",
  "IQI_M/D",
  "IQI_F/A",
  "IQI_F/B",
  "IQI_F/D",
  "PQI_R/A",
  "PQI_R/B",
  "PQI_R/D",
  "PQI_M/A",
  "PQI_M/B",
  "PQI_M/D",
  "OQI_F-GEN/A",
  "OQI_F-GEN/B",
  "OQI_F-GEN/D",
  "OQI_F-PACK/A",
  "OQI_F-PACK/B",
  "OQI_F-PACK/D",
  "OQI_FPC-100%/A",
  "OQI_FPC-100%/B",
  "OQI_FPC-100%/D",
  "OA_F-IND/D",
  "OQI_F-AUTO/A",
  "OQI_F-AUTO/B",
  "OQI_F-AUTO/D",
  "OQI_S-AUTO/A",
  "OQI_S-AUTO/B",
  "OQI_S-AUTO/D",
  "OQI_S-GEN/A",
  "OQI_S-GEN/B",
  "OQI_S-GEN/D",
  "OA_S-IND/D",
  "OQI_M/A",
  "OQI_M/B",
  "OQI_M/D",
  "JPN/D",
  "QA/D",
  "NPM/D",
];

const MACRO_PCN_INDIRECT_PRODUCTION_LINES = [
  "F_TSTE/A",
  "F_TSTE/B",
  "F_TSTE/D",
  "F_TECH/A",
  "F_TECH/B",
  "F_TECH/D",
  "F_IND/D",
  "IND/D",
  "M_TS",
  "M_IND",
  "MDS/A",
  "MDS/B",
  "MDS/D",
  "S_TSTE-F/D",
  "S_TSTE-F/A",
  "S_TSTE-F/B",
  "S_TSTE-B/D",
  "S_TSTE-B/A",
  "S_TSTE-B/B",
  "S_IND/D",
  "S_TECH-F/D",
  "S_TECH-F/A",
  "S_TECH-F/B",
  "MATERIAL/A",
  "MATERIAL/B",
  "MATERIAL/D",
  "EXC_SMT/A",
  "EXC_SMT/B",
  "EXC_SMT/D",
];

const MACRO_PCN_TOTAL_LINES = [
  ...new Set([
    ...MACRO_PCN_DIRECT_LINES,
    ...MACRO_PCN_INDIRECT_LINES,
    ...MACRO_PCN_INDIRECT_PRODUCTION_LINES,
  ]),
];

const MACRO_PCN_GROUPS = {
  Direct: MACRO_PCN_DIRECT_LINES,
  Indirect: MACRO_PCN_INDIRECT_LINES,
  "Indirect Production": MACRO_PCN_INDIRECT_PRODUCTION_LINES,
  "Macro PCN": MACRO_PCN_TOTAL_LINES,
};

const ADMIN_LINE_REGISTRY = {};
// ADMIN_LINE_REGISTRY_END
const ADMIN_VDS_FORMULA_REGISTRY = {};
// ADMIN_VDS_FORMULA_REGISTRY_END
const LINE_GROUPS = {
  "Macro PCN": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_TSTE/A",
    "F_TSTE/B",
    "F_TSTE/D",
    "F_IND/D",
  ],
  "INDIRECT": [
    "HR/D",
    "ACC/D",
    "STR/D",
    "STR/A",
    "STR/B",
    "LOG_FPC/A",
    "LOG_FPC/B",
    "LOG_FPC/D",
    "LOG_SHP/D",
    "LOG_SMT/A",
    "LOG_SMT/B",
    "LOG_SMT/D",
    "LOG_WH/D",
    "SE/D",
    "SHE/D",
    "AUT/D",
    "PLN/A",
    "PLN/B",
    "PLN/D",
    "CR/D",
    "PTE_OFF/D",
    "PTE_FAC/A",
    "PTE_FAC/B",
    "PTE_FAC/D",
    "PTE_MAC/A",
    "PTE_MAC/B",
    "PTE_MAC/D",
    "PTE_CAL/D",
    "DIE/A",
    "DIE/B",
    "DIE/D",
    "TOOL_FPC/A",
    "TOOL_FPC/B",
    "TOOL_FPC/D",
    "FIX/A",
    "FIX/B",
    "FIX/D",
    "TOOL_SMT/A",
    "TOOL_SMT/B",
    "TOOL_SMT/D",
    "TSTE-NPM/D",
    "TECH-NPM/D",
    "FA-NPM/D",
    "FPS/D",
    "TCO/D",
    "AI/D",
    "QE/D",
    "SVOQI/D",
    "SVIQI/D",
    "QA-IPQC/A",
    "QA-IPQC/B",
    "QA-IPQC/D",
    "IQI_M/A",
    "IQI_M/B",
    "IQI_M/D",
    "IQI_F/A",
    "IQI_F/B",
    "IQI_F/D",
    "PQI_R/A",
    "PQI_R/B",
    "PQI_R/D",
    "PQI_M/A",
    "PQI_M/B",
    "PQI_M/D",
    "OQI_F-GEN/A",
    "OQI_F-GEN/B",
    "OQI_F-GEN/D",
    "OQI_F-PACK/A",
    "OQI_F-PACK/B",
    "OQI_F-PACK/D",
    "OQI_FPC-100%/A",
    "OQI_FPC-100%/B",
    "OQI_FPC-100%/D",
    "OA_F-IND/D",
    "OQI_F-AUTO/A",
    "OQI_F-AUTO/B",
    "OQI_F-AUTO/D",
    "OQI_S-AUTO/A",
    "OQI_S-AUTO/B",
    "OQI_S-AUTO/D",
    "OQI_S-GEN/A",
    "OQI_S-GEN/B",
    "OQI_S-GEN/D",
    "OA_S-IND/D",
    "OQI_M/A",
    "OQI_M/B",
    "OQI_M/D",
    "JPN/D",
    "QA/D",
    "NPM/D",
    "IND/D",
  ],
  "Direct FPC": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
    "EXC_FPC/A",
    "EXC_FPC/B",
    "EXC_FPC/D",
  ],
  "Indirect FPC P460 (TE,TS,DCC,TECH,EXC)": [
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_TSTE/A",
    "F_TSTE/B",
    "F_TSTE/D",
  ],
  "Macro PCN FPC": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_TSTE/A",
    "F_TSTE/B",
    "F_TSTE/D",
    "F_IND/D",
  ],
  "Direct FPC P460(MAT),P461,P462,P463,P464,P465,P466,P468": [
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
  ],
  "Direct FPC (P461,P462,P463,P464,P465,P466,P468)": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
  ],
  "Indirect FPC (P460) TE,TS,DCC,TECH,EXC,MAT": [
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_TSTE/A",
    "F_TSTE/B",
    "F_TSTE/D",
    "F_IND/D",
    "IND/D",
  ],
  "FPC_FRONT ( MATERIAL + HOT PRESS + VAC + BLK + F-LAM + OST + AVI/K2)": [
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
  ],
  "FPC_ FIN (Line C, Line D)": [
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
  ],
  "LINE A_Automotive": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
  ],
  "Line B": [
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
  ],
  "Direct FPC_VDS (P461,P462,P463,P464,P465,P466,P468)": [],
  "Indirect FPC_VDS (P460) DCC,TECH,EXC,MAT": [
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_IND/D",
  ],
  "MATERIAL": ["MATERIAL/A", "MATERIAL/B", "MATERIAL/D"],
  "MATERIAL/A": ["MATERIAL/A"],
  "MATERIAL/B": ["MATERIAL/B"],
  "MATERIAL/D": ["MATERIAL/D"],
  "HPS & VAC": [
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC/A",
    "VAC/B",
    "VAC/D",
  ],
  "HOT PRESS": ["HOT PRESS/A", "HOT PRESS/B", "HOT PRESS/D"],
  "HOT PRESS/A": ["HOT PRESS/A"],
  "HOT PRESS/B": ["HOT PRESS/B"],
  "HOT PRESS/D": ["HOT PRESS/D"],
  "VAC": ["VAC/A", "VAC/B", "VAC/D"],
  "VAC/A": ["VAC/A"],
  "VAC/B": ["VAC/B"],
  "VAC/D": ["VAC/D"],
  "BLK": ["BLK/A", "BLK/B", "BLK/D"],
  "BLK/A": ["BLK/A"],
  "BLK/B": ["BLK/B"],
  "BLK/D": ["BLK/D"],
  "F-LAM": ["F-LAM/A", "F-LAM/B", "F-LAM/D"],
  "F-LAM/A": ["F-LAM/A"],
  "F-LAM/B": ["F-LAM/B"],
  "F-LAM/D": ["F-LAM/D"],
  "OST": ["OST/A", "OST/B", "OST/D"],
  "OST/A": ["OST/A"],
  "OST/B": ["OST/B"],
  "OST/D": ["OST/D"],
  "AVI/K2": ["AVI/K2/A", "AVI/K2/B", "AVI/K2/D"],
  "AVI/K2/A": ["AVI/K2/A"],
  "AVI/K2/B": ["AVI/K2/B"],
  "AVI/K2/D": ["AVI/K2/D"],
  "LINE A_FRONT": [
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
  ],
  "AT_FRONT": ["AT_FRONT/A", "AT_FRONT/B", "AT_FRONT/D"],
  "AT_FRONT/A": ["AT_FRONT/A"],
  "AT_FRONT/B": ["AT_FRONT/B"],
  "AT_FRONT/D": ["AT_FRONT/D"],
  "AT_VAC": ["AT_VAC/A", "AT_VAC/B", "AT_VAC/D"],
  "AT_VAC/A": ["AT_VAC/A"],
  "AT_VAC/B": ["AT_VAC/B"],
  "AT_VAC/D": ["AT_VAC/D"],
  "AT_LAM": ["AT_LAM/A", "AT_LAM/B", "AT_LAM/D"],
  "AT_LAM/A": ["AT_LAM/A"],
  "AT_LAM/B": ["AT_LAM/B"],
  "AT_LAM/D": ["AT_LAM/D"],
  "LINE A_FINAL": ["LINE A_FINAL/A", "LINE A_FINAL/B", "LINE A_FINAL/D"],
  "LINE A_FINAL/A": ["LINE A_FINAL/A"],
  "LINE A_FINAL/B": ["LINE A_FINAL/B"],
  "LINE A_FINAL/D": ["LINE A_FINAL/D"],
  "LINE B_GEN": ["LINE B_GEN/A", "LINE B_GEN/B", "LINE B_GEN/D"],
  "LINE B_GEN/A": ["LINE B_GEN/A"],
  "LINE B_GEN/B": ["LINE B_GEN/B"],
  "LINE B_GEN/D": ["LINE B_GEN/D"],
  "LINE B_NON": ["LINE B_NON/A", "LINE B_NON/B", "LINE B_NON/D"],
  "LINE B_NON/A": ["LINE B_NON/A"],
  "LINE B_NON/B": ["LINE B_NON/B"],
  "LINE B_NON/D": ["LINE B_NON/D"],
  "LINE C": ["LINE C/A", "LINE C/B", "LINE C/D"],
  "LINE C/A": ["LINE C/A"],
  "LINE C/B": ["LINE C/B"],
  "LINE C/D": ["LINE C/D"],
  "LINE D": ["LINE D/A", "LINE D/B", "LINE D/D"],
  "LINE D/A": ["LINE D/A"],
  "LINE D/B": ["LINE D/B"],
  "LINE D/D": ["LINE D/D"],
  "F_TECH": ["F_TECH/A", "F_TECH/B", "F_TECH/D"],
  "F_TECH/A": ["F_TECH/A"],
  "F_TECH/B": ["F_TECH/B"],
  "F_TECH/D": ["F_TECH/D"],
  "F_TSTE": ["F_TSTE/A", "F_TSTE/B", "F_TSTE/D"],
  "F_TSTE/A": ["F_TSTE/A"],
  "F_TSTE/B": ["F_TSTE/B"],
  "F_IND": ["F_IND/D"],
  "EXC_FPC": ["EXC_FPC/A", "EXC_FPC/B", "EXC_FPC/D"],
  "EXC_FPC/A": ["EXC_FPC/A"],
  "EXC_FPC/B": ["EXC_FPC/B"],
  "EXC_FPC/D": ["EXC_FPC/D"],
  "EXC_SMT": ["EXC_SMT/A", "EXC_SMT/B", "EXC_SMT/D"],
  "EXC_SMT/A": ["EXC_SMT/A"],
  "EXC_SMT/B": ["EXC_SMT/B"],
  "EXC_SMT/D": ["EXC_SMT/D"],
  "MDS": ["MDS/A", "MDS/B", "MDS/D", "M_TS"],
  "MDS/A": ["MDS/A"],
  "MDS/B": ["MDS/B"],
  "MDS/D": ["MDS/D"],
  "M_TS": ["M_TS"],
  "Macro SMT": [
    "MOTA_A/A",
    "MOTA_A/B",
    "MOTA_A/D",
    "MOTA_G/A",
    "MOTA_G/B",
    "MOTA_G/D",
    "MOTB/A",
    "MOTB/B",
    "MOTB/D",
    "MOTC/A",
    "MOTC/B",
    "MOTC/D",
    "AIX-MOT/A",
    "AIX-MOT/B",
    "AIX-MOT/D",
    "MOTD/A",
    "MOTD/B",
    "MOTD/D",
    "ASTP_A/A",
    "ASTP_A/B",
    "ASTP_A/D",
    "ASTP_G/A",
    "ASTP_G/B",
    "ASTP_G/D",
    "X-Ray/A",
    "X-Ray/B",
    "X-Ray/D",
    "REW/A",
    "REW/B",
    "REW/D",
    "MAS/D",
    "S_TSTE-F/A",
    "S_TSTE-F/B",
    "S_TSTE-F/D",
    "S_TECH-F/A",
    "S_TECH-F/B",
    "S_TECH-F/D",
    "BLK-1/A",
    "BLK-1/B",
    "BLK-1/D",
    "AIX-BLK/A",
    "AIX-BLK/B",
    "AIX-BLK/D",
    "BLK-2/A",
    "BLK-2/B",
    "BLK-2/D",
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
    "AELT/A",
    "AELT/B",
    "AELT/D",
    "SMT_LAM/A",
    "SMT_LAM/B",
    "SMT_LAM/D",
    "LAM MD/A",
    "LAM MD/B",
    "LAM MD/D",
    "MDLAM/A",
    "MDLAM/B",
    "MDLAM/D",
    "S_TSTE-B/A",
    "S_TSTE-B/B",
    "S_TSTE-B/D",
    "S_IND/D",
  ],
  "Macro SMT_F": [
    "AIX-MOT/A",
    "AIX-MOT/B",
    "AIX-MOT/D",
    "MOTA_A/A",
    "MOTA_A/B",
    "MOTA_A/D",
    "MOTA_G/A",
    "MOTA_G/B",
    "MOTA_G/D",
    "MOTB/A",
    "MOTB/B",
    "MOTB/D",
    "MOTC/A",
    "MOTC/B",
    "MOTC/D",
    "MOTD/A",
    "MOTD/B",
    "MOTD/D",
    "ASTP_A/A",
    "ASTP_A/B",
    "ASTP_A/D",
    "ASTP_G/A",
    "ASTP_G/B",
    "ASTP_G/D",
    "X-Ray/A",
    "X-Ray/B",
    "X-Ray/D",
    "REW/A",
    "REW/B",
    "REW/D",
    "MAS/D",
    "S_TSTE-F/A",
    "S_TSTE-F/B",
    "S_TSTE-F/D",
    "S_TECH-F/A",
    "S_TECH-F/B",
    "S_TECH-F/D",
  ],
  "Macro SMT_B": [
    "AIX-BLK/A",
    "AIX-BLK/B",
    "AIX-BLK/D",
    "AIX-ASY/A",
    "AIX-ASY/B",
    "AIX-ASY/D",
    "BLK-1/A",
    "BLK-1/B",
    "BLK-1/D",
    "BLK-2/A",
    "BLK-2/B",
    "BLK-2/D",
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
    "AELT/A",
    "AELT/B",
    "AELT/D",
    "SMT_LAM/A",
    "SMT_LAM/B",
    "SMT_LAM/D",
    "LAM MD/A",
    "LAM MD/B",
    "LAM MD/D",
    "MDLAM/A",
    "MDLAM/B",
    "MDLAM/D",
    "S_TSTE-B/A",
    "S_TSTE-B/B",
    "S_TSTE-B/D",
    "S_IND/D",
    "EXC_SMT/A",
    "EXC_SMT/B",
    "EXC_SMT/D",
  ],
  "Direct SMT": [
    "MOTA_A/A",
    "MOTA_A/B",
    "MOTA_A/D",
    "MOTA_G/A",
    "MOTA_G/B",
    "MOTA_G/D",
    "MOTB/A",
    "MOTB/B",
    "MOTB/D",
    "MOTC/A",
    "MOTC/B",
    "MOTC/D",
    "MOTD/A",
    "MOTD/B",
    "MOTD/D",
    "ASTP_A/A",
    "ASTP_A/B",
    "ASTP_A/D",
    "ASTP_G/A",
    "ASTP_G/B",
    "ASTP_G/D",
    "X-Ray/A",
    "X-Ray/B",
    "X-Ray/D",
    "REW/A",
    "REW/B",
    "REW/D",
    "MAS/D",
    "BLK-1/A",
    "BLK-1/B",
    "BLK-1/D",
    "BLK-2/A",
    "BLK-2/B",
    "BLK-2/D",
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
    "AELT/A",
    "AELT/B",
    "AELT/D",
    "LAM MD/A",
    "LAM MD/B",
    "LAM MD/D",
    "MDLAM/A",
    "MDLAM/B",
    "MDLAM/D",
    "SMT_LAM/A",
    "SMT_LAM/B",
    "SMT_LAM/D",
    "AIX-MOT/A",
    "AIX-MOT/B",
    "AIX-MOT/D",
    "AIX-BLK/A",
    "AIX-BLK/B",
    "AIX-BLK/D",
    "AIX-ASY/A",
    "AIX-ASY/B",
    "AIX-ASY/D",
    "MAS/A",
    "MAS/B",
    "EXC_SMT/A",
    "EXC_SMT/B",
    "EXC_SMT/D",
  ],
  "Indirect SMT": [
    "S_TSTE-F/A",
    "S_TSTE-F/B",
    "S_TSTE-F/D",
    "S_TECH-F/A",
    "S_TECH-F/B",
    "S_TECH-F/D",
    "S_TSTE-B/A",
    "S_TSTE-B/B",
    "S_TSTE-B/D",
    "S_IND/D",
  ],
  "SMT FRONT_DIRECT": [
    "MOTA_A/A",
    "MOTA_A/B",
    "MOTA_A/D",
    "MOTA_G/A",
    "MOTA_G/B",
    "MOTA_G/D",
    "MOTB/A",
    "MOTB/B",
    "MOTB/D",
    "MOTB_G/A",
    "MOTB_G/B",
    "MOTB_G/D",
    "AIX-MOT/A",
    "AIX-MOT/B",
    "AIX-MOT/D",
    "MOTC/A",
    "MOTC/B",
    "MOTC/D",
    "MOTD/A",
    "MOTD/B",
    "MOTD/D",
    "ASTP_A/A",
    "ASTP_A/B",
    "ASTP_A/D",
    "ASTP_G/A",
    "ASTP_G/B",
    "ASTP_G/D",
    "X-Ray/A",
    "X-Ray/B",
    "X-Ray/D",
    "REW/A",
    "REW/B",
    "REW/D",
    "MAS/D",
  ],
  "SMT FRONT_INDIRECT": [
    "S_TSTE-F/A",
    "S_TSTE-F/B",
    "S_TSTE-F/D",
    "S_TECH-F/A",
    "S_TECH-F/B",
    "S_TECH-F/D",
  ],
  "SMT BACK_DIRECT": [
    "AIX-BLK/A",
    "AIX-BLK/B",
    "AIX-BLK/D",
    "AIX-ASY/A",
    "AIX-ASY/B",
    "AIX-ASY/D",
    "BLK-1/A",
    "BLK-1/B",
    "BLK-1/D",
    "BLK-2/A",
    "BLK-2/B",
    "BLK-2/D",
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
    "AELT/A",
    "AELT/B",
    "AELT/D",
    "LAM MD/A",
    "LAM MD/B",
    "LAM MD/D",
    "MDLAM/A",
    "MDLAM/B",
    "MDLAM/D",
  ],
  "SMT BACK_INDIRECT": ["S_TSTE-B/A", "S_TSTE-B/B", "S_TSTE-B/D", "S_IND/D"],
  "ASY SMT": [
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
  ],
  "MOTA": ["MOTA_A/A", "MOTA_A/B", "MOTA_A/D"],
  "MOTA_A/A": ["MOTA_A/A"],
  "MOTA_A/B": ["MOTA_A/B"],
  "MOTA_A/D": ["MOTA_A/D"],
  "MOTA_G": ["MOTA_G/A", "MOTA_G/B", "MOTA_G/D"],
  "MOTA_G/A": ["MOTA_G/A"],
  "MOTA_G/B": ["MOTA_G/B"],
  "MOTA_G/D": ["MOTA_G/D"],
  "MOTB": ["MOTB/A", "MOTB/B", "MOTB/D"],
  "MOTB/A": ["MOTB/A"],
  "MOTB/B": ["MOTB/B"],
  "MOTB/D": ["MOTB/D"],
  "MOTB_G": ["MOTB_G/A", "MOTB_G/B", "MOTB_G/D"],
  "MOTB_G/A": ["MOTB_G/A"],
  "MOTB_G/B": ["MOTB_G/B"],
  "MOTB_G/D": ["MOTB_G/D"],
  "MOTC": ["MOTC/A", "MOTC/B", "MOTC/D"],
  "MOTC/A": ["MOTC/A"],
  "MOTC/B": ["MOTC/B"],
  "MOTC/D": ["MOTC/D"],
  "MOTD": ["MOTD/A", "MOTD/B", "MOTD/D"],
  "MOTD/A": ["MOTD/A"],
  "MOTD/B": ["MOTD/B"],
  "MOTD/D": ["MOTD/D"],
  "ASTP_A": ["ASTP_A/A", "ASTP_A/B", "ASTP_A/D"],
  "ASTP_A/A": ["ASTP_A/A"],
  "ASTP_A/B": ["ASTP_A/B"],
  "ASTP_A/D": ["ASTP_A/D"],
  "ASTP_G": ["ASTP_G/A", "ASTP_G/B", "ASTP_G/D"],
  "ASTP_G/A": ["ASTP_G/A"],
  "ASTP_G/B": ["ASTP_G/B"],
  "ASTP_G/D": ["ASTP_G/D"],
  "X-Ray": ["X-Ray/A", "X-Ray/B", "X-Ray/D"],
  "X-Ray/A": ["X-Ray/A"],
  "X-Ray/B": ["X-Ray/B"],
  "X-Ray/D": ["X-Ray/D"],
  "MAS & REW": ["REW/A", "REW/B", "REW/D", "MAS/A", "MAS/B", "MAS/D"],
  "REW": ["REW/A", "REW/B", "REW/D"],
  "REW/A": ["REW/A"],
  "REW/B": ["REW/B"],
  "REW/D": ["REW/D"],
  "MAS": ["MAS/A", "MAS/B", "MAS/D"],
  "MAS/A": ["MAS/A"],
  "MAS/B": ["MAS/B"],
  "MAS/D": ["MAS/D"],
  "BLK-1": ["BLK-1/A", "BLK-1/B", "BLK-1/D"],
  "BLK-1/A": ["BLK-1/A"],
  "BLK-1/B": ["BLK-1/B"],
  "BLK-1/D": ["BLK-1/D"],
  "BLK-2": ["BLK-2/A", "BLK-2/B", "BLK-2/D"],
  "BLK-2/A": ["BLK-2/A"],
  "BLK-2/B": ["BLK-2/B"],
  "BLK-2/D": ["BLK-2/D"],
  "ASY1_A": ["ASY1_A/A", "ASY1_A/B", "ASY1_A/D"],
  "ASY1_A/A": ["ASY1_A/A"],
  "ASY1_A/B": ["ASY1_A/B"],
  "ASY1_A/D": ["ASY1_A/D"],
  "ASY1_G": ["ASY1_G/A", "ASY1_G/B", "ASY1_G/D"],
  "ASY1_G/A": ["ASY1_G/A"],
  "ASY1_G/B": ["ASY1_G/B"],
  "ASY1_G/D": ["ASY1_G/D"],
  "ASY2": ["ASY2/A", "ASY2/B", "ASY2/D"],
  "ASY2/A": ["ASY2/A"],
  "ASY2/B": ["ASY2/B"],
  "ASY2/D": ["ASY2/D"],
  "ASY3": ["ASY3/A", "ASY3/B", "ASY3/D"],
  "ASY3/A": ["ASY3/A"],
  "ASY3/B": ["ASY3/B"],
  "ASY3/D": ["ASY3/D"],
  "AELT": ["AELT/A", "AELT/B", "AELT/D"],
  "AELT/A": ["AELT/A"],
  "AELT/B": ["AELT/B"],
  "AELT/D": ["AELT/D"],
  "SMT_LAM": ["SMT_LAM/A", "SMT_LAM/B", "SMT_LAM/D"],
  "SMT_LAM/A": ["SMT_LAM/A"],
  "SMT_LAM/B": ["SMT_LAM/B"],
  "SMT_LAM/D": ["SMT_LAM/D"],
  "LAM MD": ["LAM MD/A", "LAM MD/B", "LAM MD/D"],
  "LAM MD/A": ["LAM MD/A"],
  "LAM MD/B": ["LAM MD/B"],
  "LAM MD/D": ["LAM MD/D"],
  "MD LAM": ["MDLAM/A", "MDLAM/B", "MDLAM/D"],
  "MDLAM/A": ["MDLAM/A"],
  "MDLAM/B": ["MDLAM/B"],
  "MDLAM/D": ["MDLAM/D"],
  "S_TSTE-F": ["S_TSTE-F/A", "S_TSTE-F/B", "S_TSTE-F/D"],
  "S_TSTE-F/A": ["S_TSTE-F/A"],
  "S_TSTE-F/B": ["S_TSTE-F/B"],
  "S_TSTE-F/D": ["S_TSTE-F/D"],
  "S_TSTE-B": ["S_TSTE-B/A", "S_TSTE-B/B", "S_TSTE-B/D"],
  "S_TSTE-B/A": ["S_TSTE-B/A"],
  "S_TSTE-B/B": ["S_TSTE-B/B"],
  "S_TSTE-B/D": ["S_TSTE-B/D"],
  "S_IND/D": ["S_IND/D"],
  "S_TECH-F": ["S_TECH-F/A", "S_TECH-F/B", "S_TECH-F/D"],
  "S_TECH-F/A": ["S_TECH-F/A"],
  "S_TECH-F/B": ["S_TECH-F/B"],
  "S_TECH-F/D": ["S_TECH-F/D"],
  "SMT_VDS": [],
  "SMT_VDS-Indirect": [],
  "QA": [
    "OA_F-IND/D",
    "IQI_M/A",
    "IQI_M/B",
    "IQI_M/D",
    "IQI_F/A",
    "IQI_F/B",
    "IQI_F/D",
    "PQI_R/A",
    "PQI_R/B",
    "PQI_R/D",
    "PQI_M/A",
    "PQI_M/B",
    "PQI_M/D",
    "OQI_F-GEN/A",
    "OQI_F-GEN/B",
    "OQI_F-GEN/D",
    "OQI_F-PACK/A",
    "OQI_F-PACK/B",
    "OQI_F-PACK/D",
    "OQI_FPC-100%/A",
    "OQI_FPC-100%/B",
    "OQI_FPC-100%/D",
    "OQI_F-AUTO/A",
    "OQI_F-Auto/B",
    "OQI_F-Auto/D",
    "OA_S-IND/D",
    "OQI_S-AUTO/A",
    "OQI_S-AUTO/B",
    "OQI_S-AUTO/D",
    "OQI_S-GEN/A",
    "OQI_S-GEN/B",
    "OQI_S-GEN/D",
    "QE/D",
    "SVOQI/D",
    "SVIQI/D",
    "QA-IPQC/A",
    "QA-IPQC/B",
    "QA-IPQC/D",
    "QA/D",
  ],
  "QA_FPC": [
    "OA_F-IND/D",
    "IQI_M/A",
    "IQI_M/B",
    "IQI_M/D",
    "IQI_F/A",
    "IQI_F/B",
    "IQI_F/D",
    "PQI_R/A",
    "PQI_R/B",
    "PQI_R/D",
    "PQI_M/A",
    "PQI_M/B",
    "PQI_M/D",
    "OQI_F-GEN/A",
    "OQI_F-GEN/B",
    "OQI_F-GEN/D",
    "OQI_F-PACK/A",
    "OQI_F-PACK/B",
    "OQI_F-PACK/D",
    "OQI_FPC-100%/A",
    "OQI_FPC-100%/B",
    "OQI_FPC-100%/D",
    "OQI_F-AUTO/A",
    "OQI_F-AUTO/B",
    "OQI_F-AUTO/D",
  ],
  "QA_SMT": [
    "OA_S-IND/D",
    "OQI_S-AUTO/A",
    "OQI_S-AUTO/B",
    "OQI_S-AUTO/D",
    "OQI_S-GEN/A",
    "OQI_S-GEN/B",
    "OQI_S-GEN/D",
  ],
  "QA_IND": ["QE/D", "SVOQI/D", "SVIQI/D", "QA-IPQC/A", "QA-IPQC/B", "QA/D"],
  "QE": ["QE/D"],
  "QA/D": ["QA/D"],
  "JPN": ["JPN/D"],
  "JPN/D": ["JPN/D"],
  "SVOQI": ["SVOQI/D"],
  "SVIQI": ["SVIQI/D"],
  "QA-IPQC": ["QA-IPQC/A", "QA-IPQC/B", "QA-IPQC/D"],
  "QA-IPQC/A": ["QA-IPQC/A"],
  "QA-IPQC/B": ["QA-IPQC/B"],
  "QA-IPQC/D": ["QA-IPQC/D"],
  "OA_F-IND/D": ["OA_F-IND/D"],
  "OA_S-IND/D": ["OA_S-IND/D"],
  "IQI_M": ["IQI_M/A", "IQI_M/B", "IQI_M/D"],
  "IQI_M/A": ["IQI_M/A"],
  "IQI_M/B": ["IQI_M/B"],
  "IQI_M/D": ["IQI_M/D"],
  "IQI_F": ["IQI_F/A", "IQI_F/B", "IQI_F/D"],
  "IQI_F/A": ["IQI_F/A"],
  "IQI_F/B": ["IQI_F/B"],
  "IQI_F/D": ["IQI_F/D"],
  "PQI_R": ["PQI_R/A", "PQI_R/B", "PQI_R/D"],
  "PQI_R/A": ["PQI_R/A"],
  "PQI_R/B": ["PQI_R/B"],
  "PQI_R/D": ["PQI_R/D"],
  "PQI_M": ["PQI_M/A", "PQI_M/B", "PQI_M/D"],
  "PQI_M/A": ["PQI_M/A"],
  "PQI_M/B": ["PQI_M/B"],
  "PQI_M/D": ["PQI_M/D"],
  "OQI_F-GEN": ["OQI_F-GEN/A", "OQI_F-GEN/B", "OQI_F-GEN/D"],
  "OQI_F-GEN/A": ["OQI_F-GEN/A"],
  "OQI_F-GEN/B": ["OQI_F-GEN/B"],
  "OQI_F-GEN/D": ["OQI_F-GEN/D"],
  "OQI_F-PACK": ["OQI_F-PACK/A", "OQI_F-PACK/B", "OQI_F-PACK/D"],
  "OQI_F-PACK/A": ["OQI_F-PACK/A"],
  "OQI_F-PACK/B": ["OQI_F-PACK/B"],
  "OQI_F-PACK/D": ["OQI_F-PACK/D"],
  "OQI_FPC-100%": ["OQI_FPC-100%/A", "OQI_FPC-100%/B", "OQI_FPC-100%/D"],
  "OQI_FPC-100%/A": ["OQI_FPC-100%/A"],
  "OQI_FPC-100%/B": ["OQI_FPC-100%/B"],
  "OQI_FPC-100%/D": ["OQI_FPC-100%/D"],
  "OQI_A-AUTO": ["OQI_F-AUTO/A", "OQI_F-AUTO/B", "OQI_F-AUTO/D"],
  "OQI_F-AUTO/A": ["OQI_F-AUTO/A"],
  "OQI_F-AUTO/B": ["OQI_F-AUTO/B"],
  "OQI_F-AUTO/D": ["OQI_F-AUTO/D"],
  "OQI_S-AUTO": ["OQI_S-AUTO/A", "OQI_S-AUTO/B", "OQI_S-AUTO/D"],
  "OQI_S-AUTO/A": ["OQI_S-AUTO/A"],
  "OQI_S-AUTO/B": ["OQI_S-AUTO/B"],
  "OQI_S-AUTO/D": ["OQI_S-AUTO/D"],
  "OQI_S-GEN": ["OQI_S-GEN/A", "OQI_S-GEN/B", "OQI_S-GEN/D"],
  "OQI_S-GEN/A": ["OQI_S-GEN/A"],
  "OQI_S-GEN/B": ["OQI_S-GEN/B"],
  "OQI_S-GEN/D": ["OQI_S-GEN/D"],
  "OQI_M": ["OQI_M/A", "OQI_M/B", "OQI_M/D"],
  "OQI_M/A": ["OQI_M/A"],
  "OQI_M/B": ["OQI_M/B"],
  "OQI_M/D": ["OQI_M/D"],
  "QA_FPC-VDS": [],
  "QA_SMT-VDS": [],
  "Indidirect": ["Indidirect"],
  "HR": ["HR/D"],
  "ACC": ["ACC/D"],
  "STR": ["STR/A", "STR/B", "STR/D"],
  "STR/A": ["STR/A"],
  "STR/B": ["STR/B"],
  "STR/D": ["STR/D"],
  "LOG": [
    "LOG_SHP/D",
    "LOG_WH/D",
    "LOG_FPC/A",
    "LOG_FPC/B",
    "LOG_FPC/D",
    "LOG_SMT/A",
    "LOG_SMT/B",
    "LOG_SMT/D",
  ],
  "LOG_SHP/D": ["LOG_SHP/D"],
  "LOG_WH/D": ["LOG_WH/D"],
  "LOG_FPC": ["LOG_FPC/A", "LOG_FPC/B", "LOG_FPC/D"],
  "LOG_FPC/A": ["LOG_FPC/A"],
  "LOG_FPC/B": ["LOG_FPC/B"],
  "LOG_FPC/D": ["LOG_FPC/D"],
  "LOG_SMT": ["LOG_SMT/A", "LOG_SMT/B", "LOG_SMT/D"],
  "LOG_SMT/A": ["LOG_SMT/A"],
  "LOG_SMT/B": ["LOG_SMT/B"],
  "LOG_SMT/D": ["LOG_SMT/D"],
  "SE": ["SE/D"],
  "SHE": ["SHE/D"],
  "AUT": ["AUT/D"],
  "PLN": ["PLN/A", "PLN/B", "PLN/D", "CR/D"],
  "PTE": [
    "PTE_OFF/D",
    "PTE_FAC/A",
    "PTE_FAC/B",
    "PTE_FAC/D",
    "PTE_MAC/A",
    "PTE_MAC/B",
    "PTE_MAC/D",
    "PTE_CAL/D",
  ],
  "PTE_OFF/D": ["PTE_OFF/D"],
  "PTE_FAC/A": ["PTE_FAC/A"],
  "PTE_FAC/B": ["PTE_FAC/B"],
  "PTE_FAC/D": ["PTE_FAC/D"],
  "PTE_MAC/A": ["PTE_MAC/A"],
  "PTE_MAC/B": ["PTE_MAC/B"],
  "PTE_MAC/D": ["PTE_MAC/D"],
  "PTE_CAL/D": ["PTE_CAL/D"],
  "DIE": ["DIE/A", "DIE/B", "DIE/D"],
  "DIE/A": ["DIE/A"],
  "DIE/B": ["DIE/B"],
  "DIE/D": ["DIE/D"],
  "TOOL_FPC": ["TOOL_FPCA", "TOOL_FPCB", "TOOL_FPCD"],
  "TOOL_FPCA": ["TOOL_FPCA"],
  "TOOL_FPCB": ["TOOL_FPCB"],
  "TOOL_FPCD": ["TOOL_FPCD"],
  "TOOL_SMT": ["TOOL_SMT/A", "TOOL_SMT/B", "TOOL_SMT/D"],
  "TOOL_SMT/A": ["TOOL_SMT/A"],
  "TOOL_SMT/B": ["TOOL_SMT/B"],
  "TOOL_SMT/D": ["TOOL_SMT/D"],
  "FIX": ["FIX/A", "FIX/B", "FIX/D"],
  "FIX/A": ["FIX/A"],
  "FIX/B": ["FIX/B"],
  "FIX/D": ["FIX/D"],
  "NPM": ["TSTE-NPM/D", "TECH-NPM/D", "FA-NPM/D", "NPM/D"],
  "NPM/D": ["NPM/D"],
  "IND/D": ["IND/D"],
  "TSTE-NPM": ["TSTE-NPM/D"],
  "TECH-NPM": ["TECH-NPM/D"],
  "FA-NPM": ["FA-NPM/D"],
  "NPM_FPC/A": ["NPM_FPC/A"],
  "NPM_FPC/B": ["NPM_FPC/B"],
  "NPM_SMT/A": ["NPM_SMT/A"],
  "NPM_SMT/B": ["NPM_SMT/B"],
  "GFPS": ["FPS/D", "TCO/D", "AI/D"],
  "FPS": ["FPS/D"],
  "TCO": ["TCO/D"],
  "AI": ["AI/D"],
  "IND_VDS": [],
  "F_TSTE/D": ["F_TSTE/D"],
  "AIX-MOT": ["AIX-MOT/A", "AIX-MOT/B", "AIX-MOT/D"],
  "AIX-MOT/A": ["AIX-MOT/A"],
  "AIX-MOT/B": ["AIX-MOT/B"],
  "AIX-MOT/D": ["AIX-MOT/D"],
  "AIX-BLK": ["AIX-BLK/A", "AIX-BLK/B", "AIX-BLK/D"],
  "AIX-BLK/A": ["AIX-BLK/A"],
  "AIX-BLK/B": ["AIX-BLK/B"],
  "AIX-BLK/D": ["AIX-BLK/D"],
  "AIX-ASY": ["AIX-ASY/A", "AIX-ASY/B", "AIX-ASY/D"],
  "AIX-ASY/A": ["AIX-ASY/A"],
  "AIX-ASY/B": ["AIX-ASY/B"],
  "AIX-ASY/D": ["AIX-ASY/D"],
  "AIX-SMT": ["AIX-MOT/A", "AIX-MOT/B", "AIX-MOT/D", "AIX-BLK/A", "AIX-BLK/B", "AIX-BLK/D", "AIX-ASY/A", "AIX-ASY/B", "AIX-ASY/D"],
};

const VDS_INITIAL_FORMULA_SOURCES = {
  "Direct FPC_VDS (P461,P462,P463,P464,P465,P466,P468)":
    "Direct FPC (P461,P462,P463,P464,P465,P466,P468)",
  "SMT_VDS": "Direct SMT",
  "SMT_VDS-Indirect": "Indirect SMT",
  "QA_FPC-VDS": "QA_FPC",
  "QA_SMT-VDS": "QA_SMT",
  "IND_VDS": "INDIRECT",
};

Object.entries(VDS_INITIAL_FORMULA_SOURCES).forEach(([vdsFormula, source]) => {
  LINE_GROUPS[vdsFormula] = [...new Set(LINE_GROUPS[source] || [])];
});

const TAB_LINES = {
  "Macro PCN": ["Macro PCN", "Direct", "Indirect", "Indirect Production"],
  "FPC DATA": [
    "Macro PCN FPC",
    "Direct FPC P460(MAT),P461,P462,P463,P464,P465,P466,P468",
    "Indirect FPC P460 (TE,TS,DCC,TECH,EXC)",
    "Direct FPC (P461,P462,P463,P464,P465,P466,P468)",
    "Indirect FPC (P460) TE,TS,DCC,TECH,EXC,MAT",
    "FPC_FRONT ( MATERIAL + HOT PRESS + VAC + BLK + F-LAM + OST + AVI/K2)",
    "FPC_ FIN (Line C, Line D)",
    "LINE A_Automotive",
    "Line B",
    "Direct FPC_VDS (P461,P462,P463,P464,P465,P466,P468)",
    "Indirect FPC_VDS (P460) DCC,TECH,EXC,MAT",
    "MATERIAL",
    "MATERIAL/A",
    "MATERIAL/B",
    "MATERIAL/D",
    "HPS & VAC",
    "HOT PRESS",
    "HOT PRESS/A",
    "HOT PRESS/B",
    "HOT PRESS/D",
    "VAC",
    "VAC/A",
    "VAC/B",
    "VAC/D",
    "BLK",
    "BLK/A",
    "BLK/B",
    "BLK/D",
    "F-LAM",
    "F-LAM/A",
    "F-LAM/B",
    "F-LAM/D",
    "OST",
    "OST/A",
    "OST/B",
    "OST/D",
    "AVI/K2",
    "AVI/K2/A",
    "AVI/K2/B",
    "AVI/K2/D",
    "LINE A_FRONT",
    "AT_FRONT",
    "AT_FRONT/A",
    "AT_FRONT/B",
    "AT_FRONT/D",
    "AT_VAC",
    "AT_VAC/A",
    "AT_VAC/B",
    "AT_VAC/D",
    "AT_LAM",
    "AT_LAM/A",
    "AT_LAM/B",
    "AT_LAM/D",
    "LINE A_FINAL",
    "LINE A_FINAL/A",
    "LINE A_FINAL/B",
    "LINE A_FINAL/D",
    "LINE B_GEN",
    "LINE B_GEN/A",
    "LINE B_GEN/B",
    "LINE B_GEN/D",
    "LINE B_NON",
    "LINE B_NON/A",
    "LINE B_NON/B",
    "LINE B_NON/D",
    "LINE C",
    "LINE C/A",
    "LINE C/B",
    "LINE C/D",
    "LINE D",
    "LINE D/A",
    "LINE D/B",
    "LINE D/D",
    "F_TECH",
    "F_TECH/A",
    "F_TECH/B",
    "F_TECH/D",
    "F_TSTE",
    "F_TSTE/A",
    "F_TSTE/B",
    "F_TSTE/D",
    "F_IND",
    "MDS",
    "MDS/A",
    "MDS/B",
    "MDS/D",
    "M_TS",
  ],
  "SMT DATA": [
    "Macro SMT",
    "Macro SMT_F",
    "Macro SMT_B",
    "Direct SMT",
    "Indirect SMT",
    "SMT FRONT_DIRECT",
    "SMT FRONT_INDIRECT",
    "SMT BACK_DIRECT",
    "SMT BACK_INDIRECT",
    "ASY SMT",
    "AIX-SMT",
    "MOTA",
    "MOTA_A/A",
    "MOTA_A/B",
    "MOTA_A/D",
    "MOTA_G",
    "MOTA_G/A",
    "MOTA_G/B",
    "MOTA_G/D",
    "MOTB",
    "MOTB/A",
    "MOTB/B",
    "MOTB/D",
    "MOTB_G",
    "MOTB_G/A",
    "MOTB_G/B",
    "MOTB_G/D",
    "AIX-MOT",
    "AIX-MOT/A",
    "AIX-MOT/B",
    "AIX-MOT/D",
    "MOTC",
    "MOTC/A",
    "MOTC/B",
    "MOTC/D",
    "MOTD",
    "MOTD/A",
    "MOTD/B",
    "MOTD/D",
    "ASTP_A",
    "ASTP_A/A",
    "ASTP_A/B",
    "ASTP_A/D",
    "ASTP_G",
    "ASTP_G/A",
    "ASTP_G/B",
    "ASTP_G/D",
    "X-Ray",
    "X-Ray/A",
    "X-Ray/B",
    "X-Ray/D",
    "MAS & REW",
    "REW",
    "REW/A",
    "REW/B",
    "REW/D",
    "MAS/A",
    "MAS/B",
    "MAS/D",
    "AIX-BLK",
    "AIX-BLK/A",
    "AIX-BLK/B",
    "AIX-BLK/D",
    "BLK-1",
    "BLK-1/A",
    "BLK-1/B",
    "BLK-1/D",
    "BLK-2",
    "BLK-2/A",
    "BLK-2/B",
    "BLK-2/D",
    "ASY1_A",
    "ASY1_A/A",
    "ASY1_A/B",
    "ASY1_A/D",
    "ASY1_G",
    "ASY1_G/A",
    "ASY1_G/B",
    "ASY1_G/D",
    "ASY2",
    "ASY2/A",
    "ASY2/B",
    "ASY2/D",
    "ASY3",
    "ASY3/A",
    "ASY3/B",
    "ASY3/D",
    "AIX-ASY",
    "AIX-ASY/A",
    "AIX-ASY/B",
    "AIX-ASY/D",
    "AELT",
    "AELT/A",
    "AELT/B",
    "AELT/D",
    "SMT_LAM",
    "SMT_LAM/A",
    "SMT_LAM/B",
    "SMT_LAM/D",
    "LAM MD",
    "LAM MD/A",
    "LAM MD/B",
    "LAM MD/D",
    "MD LAM",
    "MDLAM/A",
    "MDLAM/B",
    "MDLAM/D",
    "S_TSTE-F",
    "S_TSTE-F/A",
    "S_TSTE-F/B",
    "S_TSTE-F/D",
    "S_TSTE-B",
    "S_TSTE-B/A",
    "S_TSTE-B/B",
    "S_TSTE-B/D",
    "S_IND/D",
    "S_TECH-F",
    "S_TECH-F/A",
    "S_TECH-F/B",
    "S_TECH-F/D",
    "SMT_VDS",
    "SMT_VDS-Indirect",
  ],
  "QA DATA": [
    "QA",
    "QA_FPC",
    "QA_SMT",
    "QA_IND",
    "QE",
    "SVOQI",
    "SVIQI",
    "QA-IPQC",
    "QA-IPQC/A",
    "QA-IPQC/B",
    "QA-IPQC/D",
    "OA_F-IND/D",
    "OA_S-IND/D",
    "IQI_M",
    "IQI_M/A",
    "IQI_M/B",
    "IQI_M/D",
    "IQI_F",
    "IQI_F/A",
    "IQI_F/B",
    "IQI_F/D",
    "PQI_R",
    "PQI_R/A",
    "PQI_R/B",
    "PQI_R/D",
    "PQI_M",
    "PQI_M/A",
    "PQI_M/B",
    "PQI_M/D",
    "OQI_F-GEN",
    "OQI_F-GEN/A",
    "OQI_F-GEN/B",
    "OQI_F-GEN/D",
    "OQI_F-PACK",
    "OQI_F-PACK/A",
    "OQI_F-PACK/B",
    "OQI_F-PACK/D",
    "OQI_FPC-100%",
    "OQI_FPC-100%/A",
    "OQI_FPC-100%/B",
    "OQI_FPC-100%/D",
    "OQI_A-AUTO",
    "OQI_F-AUTO/A",
    "OQI_F-AUTO/B",
    "OQI_F-AUTO/D",
    "OQI_S-AUTO",
    "OQI_S-AUTO/A",
    "OQI_S-AUTO/B",
    "OQI_S-AUTO/D",
    "OQI_S-GEN",
    "OQI_S-GEN/A",
    "OQI_S-GEN/B",
    "OQI_S-GEN/D",
    "OQI_M",
    "OQI_M/A",
    "OQI_M/B",
    "OQI_M/D",
    "QA_FPC-VDS",
    "QA_SMT-VDS",
  ],
  "IND DATA": [
    "INDIRECT",
    "HR",
    "ACC",
    "STR",
    "STR/A",
    "STR/B",
    "STR/D",
    "LOG",
    "LOG_SHP/D",
    "LOG_WH/D",
    "LOG_FPC",
    "LOG_FPC/A",
    "LOG_FPC/B",
    "LOG_FPC/D",
    "LOG_SMT",
    "LOG_SMT/A",
    "LOG_SMT/B",
    "LOG_SMT/D",
    "SE",
    "SHE",
    "AUT",
    "PLN",
    "PLN/A",
    "PLN/B",
    "PLN/D",
    "CR/D",
    "PTE",
    "PTE_OFF/D",
    "PTE_FAC/A",
    "PTE_FAC/B",
    "PTE_FAC/D",
    "PTE_MAC/A",
    "PTE_MAC/B",
    "PTE_MAC/D",
    "PTE_CAL/D",
    "DIE",
    "DIE/A",
    "DIE/B",
    "DIE/D",
    "TOOL_FPC",
    "TOOL_FPCA",
    "TOOL_FPCB",
    "TOOL_FPCD",
    "TOOL_SMT",
    "TOOL_SMT/A",
    "TOOL_SMT/B",
    "TOOL_SMT/D",
    "FIX",
    "FIX/A",
    "FIX/B",
    "FIX/D",
    "NPM",
    "TSTE-NPM",
    "TECH-NPM",
    "FA-NPM",
    "NPM_FPC/A",
    "NPM_FPC/B",
    "NPM_SMT/A",
    "NPM_SMT/B",
    "GFPS",
    "FPS",
    "TCO",
    "AI",
    "QA",
    "QA_FPC",
    "QA_SMT",
    "QA_IND",
    "QE",
    "SVOQI",
    "SVIQI",
    "QA-IPQC",
    "QA-IPQC/A",
    "QA-IPQC/B",
    "QA-IPQC/D",
    "OA_F-IND/D",
    "OA_S-IND/D",
    "IQI_M",
    "IQI_M/A",
    "IQI_M/B",
    "IQI_M/D",
    "IQI_F",
    "IQI_F/A",
    "IQI_F/B",
    "IQI_F/D",
    "PQI_R",
    "PQI_R/A",
    "PQI_R/B",
    "PQI_R/D",
    "PQI_M",
    "PQI_M/A",
    "PQI_M/B",
    "PQI_M/D",
    "OQI_F-GEN",
    "OQI_F-GEN/A",
    "OQI_F-GEN/B",
    "OQI_F-GEN/D",
    "OQI_F-PACK",
    "OQI_F-PACK/A",
    "OQI_F-PACK/B",
    "OQI_F-PACK/D",
    "OQI_FPC-100%",
    "OQI_FPC-100%/A",
    "OQI_FPC-100%/B",
    "OQI_FPC-100%/D",
    "OQI_A-AUTO",
    "OQI_F-AUTO/A",
    "OQI_F-AUTO/B",
    "OQI_F-AUTO/D",
    "OQI_S-AUTO",
    "OQI_S-AUTO/A",
    "OQI_S-AUTO/B",
    "OQI_S-AUTO/D",
    "OQI_S-GEN",
    "OQI_S-GEN/A",
    "OQI_S-GEN/B",
    "OQI_S-GEN/D",
    "OQI_M",
    "OQI_M/A",
    "OQI_M/B",
    "OQI_M/D",
    "QA_FPC-VDS",
    "QA_SMT-VDS",
    "IND_VDS",
  ],
};

const tabMenuList = [
  "Macro PCN",
  "FPC DATA",
  "SMT DATA",
  "QA DATA",
  "IND DATA",
];

const TAB_TOTAL_LINE_MAP = {
  "Macro PCN": "Macro PCN",
  "FPC DATA": "Macro PCN FPC",
  "SMT DATA": "Macro SMT",
  "QA DATA": "QA",
  "IND DATA": "INDIRECT",
};

// ลงทะเบียนสูตรคำนวณสำหรับกลุ่ม Macro PCN
LINE_GROUPS["Direct"] = [...new Set(MACRO_PCN_DIRECT_LINES)];
LINE_GROUPS["Indirect"] = [...new Set(MACRO_PCN_INDIRECT_LINES)];
LINE_GROUPS["Indirect Production"] = [
  ...new Set(MACRO_PCN_INDIRECT_PRODUCTION_LINES),
];

Object.entries(ADMIN_VDS_FORMULA_REGISTRY).forEach(([formula, rule]) => {
  const lines = [...new Set(rule.lines || [])];
  if (!formula || lines.length === 0) return;
  LINE_GROUPS[formula] = lines;
  (rule.pages || []).forEach((page) => {
    if (TAB_LINES[page] && !TAB_LINES[page].includes(formula)) {
      TAB_LINES[page].push(formula);
    }
  });
});

Object.entries(ADMIN_LINE_REGISTRY).forEach(([parentLine, rule]) => {
  const lines = [...new Set(rule.lines || [])];
  if (lines.length === 0) return;
  LINE_GROUPS[parentLine] = lines;
  lines.forEach((line) => {
    LINE_GROUPS[line] = [line];
  });
  if (rule.macroGroup && MACRO_PCN_GROUPS[rule.macroGroup]) {
    MACRO_PCN_GROUPS[rule.macroGroup].push(
      ...lines.filter(
        (line) => !MACRO_PCN_GROUPS[rule.macroGroup].includes(line),
      ),
    );
    MACRO_PCN_GROUPS["Macro PCN"].push(
      ...lines.filter((line) => !MACRO_PCN_GROUPS["Macro PCN"].includes(line)),
    );
  }
  (rule.formulaGroups || []).forEach((group) => {
    if (LINE_GROUPS[group])
      LINE_GROUPS[group].push(
        ...lines.filter((line) => !LINE_GROUPS[group].includes(line)),
      );
  });
});

module.exports = {
  MACRO_PCN_DIRECT_LINES,
  MACRO_PCN_INDIRECT_LINES,
  MACRO_PCN_INDIRECT_PRODUCTION_LINES,
  MACRO_PCN_TOTAL_LINES,
  MACRO_PCN_GROUPS,
  TAB_LINES,
  LINE_GROUPS,
  ADMIN_LINE_REGISTRY,
  ADMIN_VDS_FORMULA_REGISTRY,
  TAB_TOTAL_LINE_MAP,
};
