const express = require("express");
const router = express.Router();
const { pool_smart } = require("../../../../config");

router.post('/measurement-requests', async (req, res) => {
  const client = await pool_smart.connect();

  try {
    await client.query('BEGIN');

    // 🔒 ล็อกตารางป้องกัน Duplicate Job ID กรณีรันพร้อมกัน
    await client.query('LOCK TABLE smart.smart_qa_3d_working IN EXCLUSIVE MODE');

    // 1. รัน Sequence หา Job ID ถัดไป
    const seqQuery = `
      SELECT COALESCE(
        MAX(
          CASE 
            WHEN job_id ~ '^[0-9]{8}_[0-9]+$' 
            THEN (SPLIT_PART(job_id, '_', 2))::INTEGER 
            ELSE 0 
          END
        ), 0
      ) + 1 AS next_seq
      FROM smart.smart_qa_3d_working;
    `;
    const seqRes = await client.query(seqQuery);
    const nextSeq = seqRes.rows[0].next_seq;

    // 2. สร้าง YYYYMMDD (Asia/Bangkok)
    const dateStr = new Date()
      .toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' })
      .replace(/-/g, '');

    const autoGeneratedJobId = `${dateStr}_${nextSeq}`;

    const {
      requestId,
      requestDept,
      jobType,
      productName,
      lotNo,
      phoneNo,
      priority,
      remark, // 👈 1. รับค่า remark จาก req.body
      dueTime,
      items,
    } = req.body;

    let targetDueDate = null;
    let formattedDueTime = null;

    if (dueTime) {
      formattedDueTime = dueTime; // บันทึก string เวลาดิบไว้ที่ due_time

      // เวลาปัจจุบัน ณ ตอนที่สร้าง Request
      const now = new Date();
      const [hours, minutes] = dueTime.split(':').map(Number);

      // สร้าง Date สำหรับ Target โดยใช้วันปัจจุบันตั้งต้น
      const target = new Date(now);
      target.setHours(hours, minutes, 0, 0);

      // ถ้าเวลา Due น้อยกว่าเวลา ณ ปัจจุบัน (เช่น Request ตอน 20:00 แต่ Due คือ 03:00)
      // แสดงว่าเวลา Due เป็นของวันถัดไป -> ให้ +1 วัน
      if (target < now) {
        target.setDate(target.getDate() + 1);
      }

      targetDueDate = target;
    }

    // 3. คำนวณ totalPoint ซ้ำเพื่อความถูกต้อง
    const totalPoints = Array.isArray(items)
      ? items.reduce((sum, item) => {
        const qty = Number(item.qty) || 0;
        const measPoint = Number(item.measPoint) || 0;
        return sum + (qty * measPoint);
      }, 0)
      : 0;

    // 4. Insert ข้อมูล Master Header (เพิ่มคอลัมน์ remark)
    const headerQuery = `
      INSERT INTO smart.smart_qa_3d_working (
        job_id, 
        request_id,
        request_dept, 
        job_type, 
        product_name, 
        lot, 
        tel,
        priority, 
        total_point,
        remark,
        due_time,
        target_due_date
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
      RETURNING id, job_id;
    `;

    const headerValues = [
      autoGeneratedJobId,
      requestId || null,
      requestDept || null,
      jobType || null,
      productName || null,
      lotNo || null,
      phoneNo || null,
      priority || 'Normal',
      totalPoints,
      remark || null, // 👈 2. ส่งค่า remark ไปยัง Query Parameter ($10)
      formattedDueTime || null, 
      targetDueDate || null,    
    ];

    const headerRes = await client.query(headerQuery, headerValues);
    const savedJobId = headerRes.rows[0].job_id;
    const savedHeaderId = headerRes.rows[0].id;

    // 5. Insert ข้อมูล Detail Items
    if (items && Array.isArray(items) && items.length > 0) {
      const itemValues = [];
      const valueClauses = [];

      items.forEach((item, index) => {
        const offset = index * 5;
        valueClauses.push(
          `($${offset + 1}, $${offset + 2}, $${offset + 3}, $${offset + 4}, $${offset + 5})`
        );

        itemValues.push(
          savedJobId,
          item.requestDetails || null,
          Number(item.qty) || 0,
          item.unit || 'pcs',
          Number(item.measPoint) || 0
        );
      });

      const itemsQuery = `
        INSERT INTO smart.smart_qa_3d_working_items (
          job_id, 
          request_details, 
          qty, 
          qty_unit, 
          meas_point
        )
        VALUES ${valueClauses.join(', ')};
      `;

      await client.query(itemsQuery, itemValues);
    }

    await client.query('COMMIT');

    return res.status(201).json({
      success: true,
      message: 'บันทึกรายการวัดสำเร็จ',
      data: {
        id: savedHeaderId,
        jobId: savedJobId,
      },
    });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Insert Inspection Request Error:', error);

    return res.status(500).json({
      success: false,
      message: 'เกิดข้อผิดพลาดในการบันทึกข้อมูล',
      error: error.message,
    });
  } finally {
    client.release();
  }
});

module.exports = router;